#!/bin/sh

s6-rc-init /run/services
s6-rc change default

mkdir -p ./data
RESTART_FIFO="$(realpath ./data)/restart_fifo"
mkfifo -m 600 "$RESTART_FIFO"
echo "$RESTART_FIFO" > "/var/run/services/.s6-svscan/env/RESTART_FIFO"

exec cat < "$RESTART_FIFO"

